## This is basic continuous integration build for your Quarkus application.

name: Quarkus Codestart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        #run: ./mvnw verify -B
        run: ./mvnw package -B
      - name: install ssh key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.ORAVM }}
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: /home/runner/work/gh-actions-demo/gh-actions-demo/target/gh-actions-demo-1.0.0-SNAPSHOT-runner.jar
          host: 130.61.255.109
          remote: /opt
          port: 22
          user: ubuntu
          key: ${{ secrets.ORAVM }}
      - name: start on server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            java -jar /opt/gh-actions-demo-1.0.0-SNAPSHOT-runner.jar & disown
            && ls
          host: 130.61.255.109
          username: ubuntu
          privateKey: ${{ secrets.ORAVM }}
        env:
          CI: true